### ISSUE TITLE
Deactivate deletion of Annotation when input field is focused/edited

### ISSUE THREAD

**Issue by RESL** [StudioProcess/rvp#116]
Otherwise trying to correct a spelling mistake (clicking backspace) results in deletion of entire annotation.

**Comment by martinleopold** [comment]
The 'backspace' event will be handled by the input fields first, so they can stop it from bubbling up to the app component, which handles the hotkeys.
But actually: any keystroke should be stopped from bubbling up from input fields.. so it doesn't have side effects (like triggering hotkeys)

**Comment by martinleopold** [comment]
The angular way to do this (I think):
* Make a directive with a selector of `'input, textarea'`, so it is applied automatically to all inputs and textareas. (any other elements?)
* In the directive make a method and decorate it with `@HostListener('keydown', ['$event'])`. This will call the method with the event object as argument, whenever a `keydown` happens on the host element i.e. the `input` or `textarea`)
* Inside the method call `stopPropagation` on the event object.
* Maybe add another HostListener for `keyup` events too? Is `keypress` also needed?
