### ISSUE TITLE
Add to Information: possible Video Formats and maximum Video Size

### ISSUE THREAD

**Issue by RESL** [StudioProcess/rvp#126]

**Comment by martinleopold** [comment]
Error when storing large video file:
> The serialized value is too large (size=258433118 bytes, max=133169152 bytes).
So the max size for one Blob seems to be 127MB

**Comment by martinleopold** [comment]
Investigating Browser storing limits:
https://www.raymondcamden.com/2015/04/17/indexeddb-and-limits/

* Local Storage, Session Storage: 5MB per domain
* IndexedDB: In total about 10% of available disk space

**Comment by martinleopold** [comment]
Storage size currently limited to about 127MB, but only due to a bug in our localForage dependency (#130)

**Comment by martinleopold** [comment]
**Supported Formats** in Chrome and Firefox:

- VP8 and Vorbis in WebM
- VP9 and Opus in WebM
- Theora and Vorbis in Ogg
- H.264 and MP3 in MP4
- H.264 and AAC in MP4

Safari: H264 formats

Preferred format: **H.264 and AAC in MP4**

**Comment by martinleopold** [comment]
@RESL size and format infos researched (see above) and ready for docs and info popup
