### ISSUE TITLE
Include version/build in app frontend

### ISSUE THREAD

**Issue by martinleopold** [StudioProcess/rvp#164]
The version + build info should be included in the frontend (probably in the settings dialog for now).

The version number is tracked in `package.json`'s `version` property.

A build number is something that's incremented with every (successful) compilation. It's somewhat unreliable though, since multiple people are commiting. Better we use the compilation hash + timestamp.

**Comment by dinony** [comment]
Not entirely sure what is meant by compilation hash, but I've proposed a [PR](https://github.com/StudioProcess/rvp/pull/167), where the (built time) git commit hash is shown.
git commit hash + lock file should be pretty unique.

**Comment by martinleopold** [comment]
PR looks good but how should we best deal with the `package.json` version number i.e. when and how should we increment it? 
I think as soon as anything changes online it should be reflected in the version number. Can we make the git commit hash part of the version number? Is it possible with semver?

**Comment by martinleopold** [comment]
done in current builds
