### ISSUE TITLE
audio tracks & workflow thoughts

### ISSUE THREAD

**Issue by leaklaue** [StudioProcess/rvp#176]
Hi there! Today I got to think about how to rapidly use the RV prototype while on research in the field. When it's not collaborative filming and I film on my own I use my GH4 camera and a separate H6 Zoom which I connect with various microphones according to surrounding and setting. When I get back to my computer and check the material, I usually only watch the video file with the "bad" sound recording from the camera in-built microphone. Though sometimes, actually often, the surrounding sounds make it impossible to hear properly, so I need to sync my better mic sound channels with my video file. Therefore I use the software PluralEyes. Then I check my material directly in PluralEyes or export a timeline to Premiere. In order to use it then in the RV protoype, I would have to export a video file, and then upload it to the prototype, which would be quite a hassle (GH4 video material is 4K). Are there any thoughts or ideas or possibilities to add sound and sync it - or add a PluralEyes file or something like this?
Thanks!
Léa

**Comment by dinony** [comment]
Hi Lea,
that sounds like a laborious workflow. I like the idea of syncing audio and video but it's up to the project lead to decide on budget and actual feature implementations. 
I would guess that this is out of scope :) /cc @martinleopold

**Comment by martinleopold** [comment]
suggestions added to feedback doc
