### ISSUE TITLE
'New Project' Button

### ISSUE THREAD

**Issue by martinleopold** [StudioProcess/rvp#187]
* In the `Project` modal window, add new button `New` with description `New project`.
* Has a red color and a warning modal just like the current `Reset` button. The warning modal reads: `Create a new (empty) project? All data will be lost.`
* Creates completely empty project with one track named `Track 1` and no annotations
* Change `Reset`-button description (currently reads `Reset project`) to `Reset to sample project`

**Comment by martinleopold** [comment]
@dinony Just added this to Tasks for Research Academy as second to last priority

**Comment by RESL** [comment]
- [ ] Clicking the button results in wrong length of timeline: see #192

**Comment by dinony** [comment]
Ok, should be fixed with @martinleopold commit?

**Comment by martinleopold** [comment]
@dinony If it's the right fix from your point of view, then yes.

**Comment by dinony** [comment]
Hmm seems to work now, maybe it was really the missing null check. I just noticed that the button was ok again :)
