### ISSUE TITLE
Active track (i.e. destination for add and paste actions)

### ISSUE THREAD

**Issue by martinleopold** [StudioProcess/rvp#193]
- [x] introduce concept of an active track. the last last clicked track becomes active. 
- [x] 'add annotation' action should place new annotation _at the playhead position in the active track_ 
- [x] 'paste annotation(s)' action should place annotations _at the playhead position in the active track_
- [x] the currently active track is marked with a black bar on the left side: <img width="1340" alt="active_track_line" src="https://user-images.githubusercontent.com/1692826/47033413-016b7b00-d175-11e8-9bcf-bf8b2beb598e.png">

**Comment by martinleopold** [comment]
- [ ] remove behviour: 'hover over track' to designate paste target

**Comment by dinony** [comment]
What about `shift` or `ctrl` click on timeline?

**Comment by martinleopold** [comment]
'Hover over track' behaviour is fixed now, thx!
Just noted a few other things:
- [ ] Like in the mockup above, the black bar should actually be *outside* of the track so it doesn't overlap anything on the track. Also make it 3px (like the annotation-selection)

I'm reluctant to use shift or ctrl click since this is traditionally used for multi-select – and we do it to for annotations. Therefore:
- [ ] Let's use `click on the colored dot at the beginning of the track` for selecting the track without setting the cursor.

**Comment by martinleopold** [comment]
- [ ] Fix Buggy undo behaviour
To reproduce:
* Reset to sample project
* Click 3rd track ('Line')
* Reset to sample project again
* Undo button is available (black). Press it.
* 3rd track gets selected

Another one:
* Reset to sample project
* Click 2nd track ('dot')
* Press undo. Track becomes deslected, playhead moves to beginning (should it do all that?)
* Press redo. Track becomes selected again.
* Reload page.
* Page starts with 2nd track selected.

What is actually the desired behaviour for track selection and undo? 

And I noted:
- [ ] Selecting an annotation and pressing undo deselects it. Even though the Undo button is grayed out. Is this a bug?

**Comment by dinony** [comment]
> Like in the mockup above, the black bar should actually be outside of the track so it doesn't overlap anything on the track. Also make it 3px (like the annotation-selection)

The `timeline-wrapper` div has `overflow: hidden`set. Do you have any idea how to solve this?
