### ISSUE TITLE
Double-click annotations

### ISSUE THREAD

**Issue by martinleopold** [StudioProcess/rvp#194]
- [x] double click on annotation in timeline: should move the playhead to the begin time of the annotation (instead of creating a new annotation)
- [x] double click on annotation in inspector: should move the playhead to the begin time of the annotation. double click is registered only on 'unused' space i.e. space that is not an input element or symbol

**Comment by martinleopold** [comment]
Bug: the playhead jumps to the right time, but the video does not. Thus, when playing, the video continues from the old time.

**Comment by dinony** [comment]
Ah thanks, should be ok with the latest commits.
