### ISSUE TITLE
Title Feature: Production Build Error

### ISSUE THREAD

**Issue by martinleopold** [StudioProcess/rvp#207]
Commit https://github.com/StudioProcess/rvp/commit/d5a70812e95809759b409669a9a7a6c8c7f49e73 (Branch `feature_title`):

Bei `npm run build:prod` treten zwei Fehlermedlungen auf:
`ERROR in src/app/core/components/main/main.html(5,14): : Property 'project_title' does not exist on type 'MainContainer'.
src/app/core/components/titlebar/titlebar.component.html(2,42): : Property 'pnform' is private and only accessible within class 'TitlebarComponent'.`

`npm start` und `npm run build` funktionieren fehlerfrei. Habe testweise 'project_title' bei `src/app/core/components/main/main.html(5,14)` gelöscht und 'pnform' bei `src/app/core/components/titlebar/titlebar.component.html(2,42)` nicht private gemacht, dann verschwinden die Fehler.  Sollte also nichts Großes sein, aber bitte schau Du mal rein, @n0mad01

**Comment by n0mad01** [comment]
@martinleopold genau wie du sagtest, pnform darf nicht private sein und die project_title property ist nicht notwendig, seltsam das der dev build das nicht schon aufgezeigt hat, sollte jetzt jedenfalls gefixt sein.

**Comment by martinleopold** [comment]
@martinleopold danke!
