### ISSUE TITLE
View Mode: Disable shortcuts

### ISSUE THREAD

**Issue by RESL** [StudioProcess/rvp#219]
Tested on branch `feat/viewmode` (24bb451)

When View Mode is active, disable these _shortcuts_:

- `Dbl Click in Timeline` (add new annotation)
- `backspace` (deletes selected annotations)
- `+ or ]` (add new Track)
- `Cmd + C` (copy selected annotations)
- `Cmd + V` (paste annotations)
- `CMD + Left Click` (select multiple annotations)
- `Shift + Left Click` (select range of annotations)
- `CMD + Z` (Undo)
- `CMD + Shift + Z` (Redo)

Feature concept: [View Mode](https://docs.google.com/document/d/1rfWIZxU4F5_dZr6F5pDconWSYt5PPs1BvGnuNBnakVY/edit#)

**Comment by martinleopold** [comment]
Tested on branch master (f40361ef):

Using Test URL: https://rv-dev.process.studio/?video=https%3A%2F%2Ftest.madek.zhdk.ch%2Fapi%2Fmedia-entries%2Fe07019ca-4538-4127-83d6-c604012a6073%2Fmedia-file%2Fdata-stream&annotations=https%3A%2F%2Ftest.madek.zhdk.ch%2Fapi%2Fmedia-entries%2Fe07019ca-4538-4127-83d6-c604012a6073%2Fmeta-data%2Fresearch_video%3Arv_annotations%2Fdata-stream

Some shortcuts are currently disabled but should be still working:
* `spacebar` (play/pause)
* `click/drag the timeline scrollbar` (scrolls and zooms the timeline)
* `Project` button in menu bar (only way to get out of view mode, by opening another project)

<img width="1177" alt="Screenshot 2020-06-25 at 10 31 49" src="https://user-images.githubusercontent.com/1692826/85685667-8ee3ca00-b6cf-11ea-8a96-e4044265c469.png">

**Comment by RESL** [comment]
<img width="1648" alt="Screenshot 2020-08-13 at 09 32 45" src="https://user-images.githubusercontent.com/4606254/90107372-ff5ead00-dd48-11ea-81eb-84e20f05ca52.png">

Using test URL doesn't work. Madek server doesn't work.
```
{
  "headers": {
    "normalizedNames": {},
    "lazyUpdate": null,
    "headers": {}
  },
  "status": 0,
  "statusText": "Unknown Error",
  "url": "https://test.madek.zhdk.ch/api/media-entries/e07019ca-4538-4127-83d6-c604012a6073/meta-data/research_video:rv_annotations/data-stream",
  "ok": false,
  "name": "HttpErrorResponse",
  "message": "Http failure response for https://test.madek.zhdk.ch/api/media-entries/e07019ca-4538-4127-83d6-c604012a6073/meta-data/research_video:rv_annotations/data-stream: 0 Unknown Error",
  "error": {
    "isTrusted": true
  }
}
```

**Comment by RESL** [comment]
Madek Test server online (August 14, 2020). 
Test successful.
