### ISSUE TITLE
URL in annotation: clickable link mistakenly converted into normal text

### ISSUE THREAD

**Issue by RESL** [StudioProcess/rvp#242]
Tested on branch `feat/extra` (c4886267)

URL mistakenly converted into normal text, when it should remain clickable Link.

**Here is a step-by-step explanation for reproduction:**
1. Reset to sample project.
2. Select text field of empty annotation (in red track, starting at `00:00:06.736`, ending at `00:00:21.197`)
3. add URL `https://process.studio/` as annotation text
4. select annotation beneath by left-clicking annotation in yellow track -> URL in previous annotation is converted into clickable Link (correct)
5. Select original annotation again (not textfield of that annotation) -> URL is converted back into normal text, not clickable (wrong)
6. Select different annotation -> URL is still normal text, should be clickable Link (wrong)

Clickable URLs should only be converted into normal text, when text field of annotation is selected (i.e. while typing). If anything else is selected (another annotation or anything else in same annotation other than the textfield), URL should remain clickable link.

**Here is a step-by-step explanation for reproduction (with screenshots):**

**1.** Reset to sample project.

**2.** Select text field of empty annotation (in red track, starting at `00:00:06.736`, ending at `00:00:21.197`)
<img width="1626" alt="Screenshot 2020-09-09 at 10 39 39" src="https://user-images.githubusercontent.com/4606254/92576662-129e6300-f28a-11ea-9b4a-95fce5c9fa3a.png">

**3.** add URL `https://process.studio/` as annotation text
<img width="1626" alt="Screenshot 2020-09-09 at 10 39 55" src="https://user-images.githubusercontent.com/4606254/92576735-25b13300-f28a-11ea-8c1b-a23a5108b764.png">

**4.** select annotation beneath by left-clicking annotation in yellow track -> URL in previous annotation is converted into clickable Link (correct)
<img width="1626" alt="Screenshot 2020-09-09 at 10 40 09" src="https://user-images.githubusercontent.com/4606254/92576765-2ea20480-f28a-11ea-85ae-36b7d910b8d9.png">

**5.** Select original annotation again (not textfield of that annotation) -> URL is converted back into normal text, not clickable (wrong)
<img width="1626" alt="Screenshot 2020-09-09 at 10 40 20" src="https://user-images.githubusercontent.com/4606254/92576831-411c3e00-f28a-11ea-9ed9-4c4d9d304807.png">

**6.** Select different annotation -> URL is still normal text, should be clickable Link (wrong)
<img width="1626" alt="Screenshot 2020-09-09 at 10 40 57" src="https://user-images.githubusercontent.com/4606254/92576860-4b3e3c80-f28a-11ea-8253-5204d574b237.png">

**Comment by RESL** [comment]
Issue fixed except for one case:

- Repeat steps 1. - 3. (see above)
- After clicking on link in annotation (new tab opens) and returning to RV tab, the clicked link is mastakenly converted into normal text again

**Comment by martinleopold** [comment]
Tested after update; Fixed (eeda7a50)
