### ISSUE TITLE
Hiding track leads to empty track

### ISSUE THREAD

**Issue by RESL** [StudioProcess/rvp#244]
Tested on branch `feat/extra` (2526e6b3)

Hiding a track, applying search (with `apply to timeline` enabled) leads to empty track.

1. Reset to sample project
2. Select any empty annotation, add text _UUUU_ 
3. Search for _UUUU_ -> correct result appears
4. Click `apply to timeline`
5. Hide track containing said annotation by clicking `eye symbol` -> track is hidden correctly
6. Click `eye symbol` to show track again -> track is mistakenly empty

**Comment by martinleopold** [comment]
Fixed (tested with eeda7a50)
