### ISSUE TITLE
Project Handling Popup

### ISSUE THREAD

**Issue by martinleopold** [StudioProcess/rvp#26]

**Comment by RESL** [comment]
- [ ] Open Project (dialogue)
- [ ] Export Project (zip, dialogue?)
- [ ] Load Video File (dialogue)
- [ ] Reset Project (dialogue)

**Comment by martinleopold** [comment]
native warning/confirm dialogue: https://developer.mozilla.org/en-US/docs/Web/API/Window/confirm
