### ISSUE TITLE
State Management/Design

### ISSUE THREAD

**Issue by martinleopold** [StudioProcess/rvp#77]
* Organise according to persistent vs volatile
  * Which data that needs to be saved to persistent storage?
  * Which data that needs to be saved infrequently?
  * Which data that can be lost between sessions?
* Organise according to access/update pattern
  * Which data is commonly updated together?

**Comment by RESL** [comment]
![img_2035](https://cloud.githubusercontent.com/assets/4606254/17027769/7b9efba2-4f65-11e6-83ff-9fd3a94eb28a.JPG)
