### ISSUE TITLE
Input validation for Entry Component

### ISSUE THREAD

**Issue by RESL** [StudioProcess/rvp#80]
How to use pipes with [(ngModel)]?

https://angular.io/docs/ts/latest/guide/forms.html
http://blog.angular-university.io/introduction-to-angular-2-forms-template-driven-vs-model-driven/
https://medium.com/@daviddentoom/angular-2-form-validation-9b26f73fcb81#.go194sm31 (deprecated?)

**Comment by martinleopold** [comment]
Done. 634a19af2d4e067fb360751d8cd2836befe676cd
