### ISSUE TITLE
Update reducers to use immutable data

### ISSUE THREAD

**Issue by martinleopold** [StudioProcess/rvp#86]
- If an object in the state needs to be changed, use a new object instead of mutating the old one.
- Then we can use ChangeDetectionStrategy.OnPush in the affected components to get performance benefits.
- Might be good for this to review the model data structures in general. (#87)

**Comment by martinleopold** [comment]
Libraries for immutable data:
* https://github.com/facebook/immutable-js/
* https://github.com/rtfeldman/seamless-immutable
* https://github.com/swannodette/mori

**Comment by dinony** [comment]
Fixed in [v0.1.0](https://github.com/StudioProcess/rvp/blob/v0.1.0/CHANGELOG.md)
