### ISSUE TITLE
Refactor model data structure

### ISSUE THREAD

**Issue by martinleopold** [StudioProcess/rvp#87]
It seems to be hard to deal with, due to deep nesting. E.g. a specific annotation is at: `Project.timeline.tracks[i].annotations[j]`. Could help with DB/persistence too.

Keywords: normalised, flat structure

See: 
- https://github.com/reactjs/redux/issues/994#issuecomment-153341165
- https://github.com/paularmstrong/normalizr
- https://github.com/reactjs/redux/issues/1255#issuecomment-173232953
- https://www.firebase.com/docs/web/guide/structuring-data.html

**Comment by martinleopold** [comment]
More thoughts:
* Integrate video data into the model. Currently it’s separated and it’s hard to see whats going on, since there are different flows of data going on.

**Comment by dinony** [comment]
Fixed in [v0.1.0](https://github.com/StudioProcess/rvp/blob/v0.1.0/CHANGELOG.md)
