### ISSUE TITLE
Edit annotation in inspector: two clicks required to edit input fields (first click = selection, second click = edit fields)

### ISSUE THREAD

**Issue by RESL** [StudioProcess/rvp#93]
selection of annotation and possibility to edit input fields should be possible with one click instead of two.

**Comment by martinleopold** [comment]
Maybe the DOM gets re-built because of ngFor? 

See [here](https://angular.io/docs/ts/latest/api/common/index/NgFor-directive.html):
> Angular uses object identity to track insertions and deletions within the iterator and reproduce those changes in the DOM. 

If so use ngForTrackBy to fix this.

**Comment by martinleopold** [comment]
Looks like object equality changes for **every** entry if **any** entry is selected or deselected, thus recreating **all** entries in the DOM.

**Comment by martinleopold** [comment]
Closed in upcoming commit.
