### ISSUE TITLE
Refactor scroll-zoom directive

### ISSUE THREAD

**Issue by martinleopold** [StudioProcess/rvp#98]
- Scroll position is set in absolute values (px) instead of percent.
- Drop container-selector, as it was just needed to calculate the absolute scroll position. This will no be handles by the time service.
- Zoom needs to be renamed to what it actually does, namely sizing (width) or expanding the element. Consequently also rename the directive.

Might be related to the bug described in #95.

**Comment by dinony** [comment]
Fixed in [v0.1.0](https://github.com/StudioProcess/rvp/blob/v0.1.0/CHANGELOG.md)
